Assets/FX/Material/KailR_Circle.mat

branch : iyuna6577/'이유나 2021/09/15 ) 카일 궁 수정'

---

Assets/FX/Animation/Kail_R.controller
Assets/FX/prefab/FX_Atler_Smoke.prefab
Assets/FX/prefab/Kail_R.cs
Assets/FX/prefab/Kail_R.cs.meta
Assets/Scripts/Kali.cs

branch : PooHappy / '배수용' - 2021/09/15 ) 카일 궁극기 이펙트 적용

---

Assets/Scripts/BuildingController.cs

tornadoblot / '명지연 - 2021/11/12 ) 워크샵 건설 버그 수정'

tornadoblot / '명지연 - 2021/11/12 ) 워크샵 건설 버그 수정'

---

Assets/Character/Kyle/kyle(finish).FBX.meta
Assets/Scripts/FreaksController.cs
Assets/Scripts/ObjectPooling.cs

1. 공격 코드
2. 죽음 코드
3. 공격 당했을 때의 코드
4. 플레이어 오브젝트에게 접근 코드
완료

'조소연- 2021/11/12 ) 블랙프릭스 공격 및 접근 순서 코드 생성'

---

Assets/Scripts/CameraController.cs

branch :Anti9uA / '심규보 - 2021/11/12 ) 카메라 잔버그 수정'

---

Assets/Prefabs/White Freaks.prefab

iyuna6577 - 2021/11/13 ) 파일 정리

---

Assets/Scripts/SpawnController.cs

코드상으로만 수정했습니다
실제 실행은 현재 블랙 프릭스에 버그가 있어 테스트 하지 못했으니 작업 완료되면 다시 재개하겠습니다

tornadoblot / '명지연- 2021/11/13 ) 레이지모드 오브젝트 풀링 수정'

---

Assets/Material/Workshop_Large.mat
Assets/Material/Workshop_Leg.mat
Assets/Material/Workshop_Medium.mat
Assets/Material/Workshop_Small.mat
Assets/Prefabs/Alter.prefab
Assets/Prefabs/Switch.prefab
Assets/Prefabs/White Freaks.prefab
Assets/Scripts/AlterController.cs
Assets/Scripts/BuildingController.cs
Assets/Scripts/BuildingPreview.cs
Assets/Scripts/SwitchController.cs
Assets/Scripts/WorkshopController.cs

tornadoblot-/-'명지연---2021/11/27-)-알터-크기-변경-및-작업'

---

Assets/Character/stone.fbx.meta
Assets/Scripts/GameController.cs

1) 이제 스킬을 사용하면 쿨타임을 표시하는 타이머와 게이지가 작동합니다.
/////
1) UI 가시성을 위해 UI 타이머 텍스트를 숨김 처리할 예정입니다.

스킬 쿨타임 UI 작업 완료

---

Assets/Scripts/CameraController.cs

'심규보 - 2022/01/07 ) 카메라 및 피벗 수정'

---

Assets/Scripts/SpawnController.cs
Assets/Scripts/WorkshopController.cs

tornadoblot / '명지연 - 2022/01/15 ) 워크샵 머티리얼 수정'

tornadoblot / '명지연 - 2022/01/15 ) 워크샵 머티리얼 수정'

---

ProjectSettings/TagManager.asset

포스트 프로세싱 레이어 수정

---

Assets/Material/Workshop_Yellow.mat
Assets/Material/Workshop_Yellow.mat.meta

1. 노란색 워크샵 추가 : Assets\Material\Workshop_Yellow
2. map 씬 작업 : 테두리 물가 추가

맵 작업 및 워크샵 추가

---

Assets/Art/FX/prefab/Fx_White_Projectile.prefab
Assets/Material/Range_No.mat
Assets/Material/Range_No.mat.meta
Assets/Prefabs/TowerBullet.prefab
Assets/Prefabs/WhiteTowerBullet.prefab
Assets/Prefabs/WhiteTowerBullet.prefab.meta
Assets/Scripts/BulletPooling.cs
Assets/Scripts/BulletPooling.cs.meta
Assets/Scripts/TowerAttack.cs
Assets/Scripts/WhiteTowerAttack.cs
Assets/Scripts/WhiteTowerAttack.cs.meta
Assets/Scripts/WhiteTowerBullet.cs
Assets/Scripts/WhiteTowerBullet.cs.meta

1. 화이트타워 구현
화이트타워 건설불가범위는 따로 화이트타워 하위(자식) 오브젝트로 시각화하였고, Layer는 Building으로 했습니다.
건설할때 좌표받아오는 함수는 WhiteTowerAttack 클래스의 public void SetPosition(Vector3 pos) 입니다.
2. Bulletpooling생성
화이트타워의 총알들은 모두 들어가 있는 상태이고,
알터와 블랙타워에서 생성되는 공격총알들도 모두 이 pooling에 넣을것입니다.

화이트타워구현/ 총알pooling 생성

---

Assets/Scripts/AlterController.cs
Assets/Scripts/GameManager.cs

+) 알터건설 불가능범위radius전달 함수 추가
GameManager.getAlterNoBuildRadius()
사용하시면 됩니다

알터건설 불가능범위radius전달 함수 추가

---

Assets/MeshBaker/Examples/CharacterCustomization/blenderFile.unitypackage.meta
Assets/MeshBaker/Examples/Examples_HDRP.unitypackage.meta
Assets/MeshBaker/Examples/Examples_URP.unitypackage.meta
Assets/Prefabs/Workshop/WorkShop_Tex.mat
Assets/Scripts/AlterController.cs
Assets/Scripts/BulletPooling.cs
Assets/Scripts/Structure/Building.cs
Assets/Scripts/Structure/BuildingManager.cs
Assets/Scripts/Structure/WorkshopController.cs
Assets/Scripts/Structure/WorkshopController.cs.meta
Assets/Scripts/Structure/WorkshopStat.cs
Assets/Scripts/SwitchController.cs

기존에 BuildingManager에게 위치 넘겨줄때 사용한 함수
" SetBuildPosition " 를 사용하기 전에 (워크샵의 경우) BuildingManager 클래스에 있는
public void SetEssenceSpot(GameObject go) 
{
essenceSpot = go;
}
함수를 먼저 코드로 적어주셔서 자원지(Arrow) 게임오브젝트를 
넘겨주시면 워크샵 색이 거기에 맞춰서 바뀔겁니다

현명은 / 워크샵 기능 구현

---

Assets/Art/FX/prefab/FX_Construc_WhiteTower.prefab
Assets/Prefabs/Alter.prefab
Assets/Prefabs/Workshop/Materials.meta
Assets/Prefabs/Workshop/Materials/WorkShop_Tex.mat
Assets/Prefabs/Workshop/Materials/WorkShop_Tex.mat.meta
Assets/Scripts/EssenceSpot.cs
Assets/Scripts/Structure/Building.cs
Assets/Scripts/Structure/BuildingManager.cs
Assets/Scripts/Structure/BuildingRange.cs
Assets/Scripts/Structure/WorkshopController.cs

1. 워크샵의 자원지에 따른 색상설정방법을 변경
2. 건물관련 오브젝트 건설표시(반투명) 제작
3. 알터, 화이트타워의 경우 건설중 제작
건물들의 경우 일단 잘 작동이 되는지 확인하기위해 임의 시간(10초)을 두어 건설중인 모습이 보이도록 하였으며, 추후에 화이트프릭스가 올 경우 건설이 되도록 할 예정

현명은 / 건설표시 및 건설중 제작

---

Assets/Art/FX/prefab/FX_Atler_Smoke.prefab
Assets/Prefabs/Workshop/WorkShop_Tex.mat
Assets/Prefabs/build_alter.prefab
Assets/Prefabs/build_alter.prefab.meta
Assets/Prefabs/build_whitetower.prefab
Assets/Prefabs/build_whitetower.prefab.meta
Assets/Prefabs/build_workshop.prefab
Assets/Prefabs/build_workshop.prefab.meta
Assets/Scripts/AlterAttack.cs
Assets/Scripts/Structure/Building.cs
Assets/Scripts/Structure/BuildingManager.cs
Assets/Scripts/Structure/BuildingPooling.cs
Assets/Scripts/Structure/BuildingPooling.cs.meta
Assets/Scripts/Structure/WorkshopController.cs
Assets/Scripts/Structure/WorkshopState.cs
Assets/Scripts/TowerAttack.cs
Assets/Scripts/WhiteTowerAttack.cs

1. 빌딩 오브젝트 풀링 추가
2. 기존 워크샵 FadeOut 버그 수정

Wise_eun / '현명은 - 2022/05/20 ) 빌딩풀링추가 및 워크샵FadeOut수정'

---

Assets/Prefabs/whitefreaks.prefab
Assets/Scripts/Structure/Building.cs
Assets/Scripts/Structure/WhiteFreaksManager.cs
Assets/Scripts/Structure/WhiteFreaksManager.cs.meta
Assets/Scripts/WhiteFreaksController.cs

1. 화이트프릭스매니저를 생성하여 놀고있는 화이트프릭스/일하고있는 화이트프릭스의 수를 체크하는 역할 및 화이트프릭스와 다른 클래스의 중간다리 역할을 합니다.
2. 화이트프릭스가 해당 목적지까지 가는것을 구현하였으나, 도착했을때의 이벤트를 어떻게하면 효율적으로 할 수 있을지에 대해서는 현재 계속 찾아보고있습니다.
(이 과정에서 새로운 기술들을 공부하면서 알아보다보니 시간이 걸릴것같아 일단 화이트프릭스 매니저까지의 코드를 올려놓았습니다.)

Wise-eun / '현명은 - 2022/05/24 ) 화이트프릭스매니저 생성'

---

Assets/Prefabs/build_whitetower.prefab
Assets/Scripts/TowerAttack.cs
Assets/Scripts/WhiteTowerAttack.cs

화이트타워 디졸브 관련해서 머티리얼 텍스쳐는 추후에 적용된다고합니다.
먼저 디졸브 머티리얼만 적용하였습니다.

Wise-eun / '현명은 - 2022/06/03 ) 화이트타워 붕괴시, 디졸브 적용'

---

Assets/Prefabs/build_alter.prefab
Assets/Prefabs/build_whitetower.prefab
Assets/Prefabs/build_workshop.prefab
Assets/Scenes/Map.unity

기존 사운드의 경우, 거리에따라 소리의 높낮이가 변하는 문제
해당 문제는 3D사운드를 이용했어서 도플러 효과가 자동으로 들어가져 있는게 원인이었습니다! 해당 사운드들 모두 doppler level =0 으로 맞춰주니 해결하였습니다!

Wise-eun / '현명은 - 2022/06/05 ) 사운드관련 문제 해결'

---

Assets/Art/FX/Shader/Unlit_Particle_HDR_Heal 2.mat

Update Unlit_Particle_HDR_Heal 2.mat

---

Assets/Scripts/InfoUI.cs
Assets/Scripts/PauseUIController.cs

1. ESC옵션창 에러 수정
2. 패시브 스킬 알림창 수정

Wise-eun / '현명은 - 2022/08/09)  피드백반영 '

---

Assets/Scripts/Structure/WhiteFreaksManager.cs
Assets/Scripts/Structure/WorkshopState.cs
Assets/Scripts/WhiteFreaksController.cs

Wise-eun / '현명은 - 2022/08/19) 화이트프릭스관련 버그 수정 '

---

Assets/Art/FX/prefab/FX_Warron_E_Audacious Charge.prefab

이유나 - 2022/08/26)  성민님 요청 사항
